SELECT birthdate
FROM people;
SELECT birthdate,
    DATEDIFF(CURDATE(), birthdate)
FROM people;
SELECT DATE_ADD(CURDATE(), INTERVAL 1 YEAR);
SELECT DATE_SUB(CURDATE(), INTERVAL 1 YEAR);
SELECT TIMEDIFF(CURTIME(), '07:00:00');
SELECT NOW() - INTERVAL 18 YEAR;